
:: Generic Data ------------------------------------
TARGET_NAME/mcg2
DEVTYPE/nrt2ppc
DEVTARGET/nrt2mcg2
SCIDEVTYPE/nrt2ppc
SOURCE/bt

:: SCI generic data -------------------------------------------
RESERVED/0000
FUNCTION/mcg

:: SCI 1 Data -------------------------------------------
SCI1SUBFCT/stand
SCI1VERSION/4.22.0.2

:: SCI 2 Data --------------------------------------------
SCI2SUBFCT/gsmdump
SCI2VERSION/2.0.3.0

:: SCI 3 Data --------------------------------------------
SCI3SUBFCT/videostrm
SCI3VERSION/1.1.2.0
