# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Wed Mar 13 06:14:55 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 674)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName("tabWidget")
        self.tabRelease = QtWidgets.QWidget()
        self.tabRelease.setObjectName("tabRelease")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabRelease)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tabRelease)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.cbMcgFwVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgFwVersions.sizePolicy().hasHeightForWidth())
        self.cbMcgFwVersions.setSizePolicy(sizePolicy)
        self.cbMcgFwVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbMcgFwVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbMcgFwVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgFwVersions.setEditable(True)
        self.cbMcgFwVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgFwVersions.setObjectName("cbMcgFwVersions")
        self.horizontalLayout_8.addWidget(self.cbMcgFwVersions)
        self.label_8 = QtWidgets.QLabel(self.tabRelease)
        self.label_8.setMinimumSize(QtCore.QSize(70, 0))
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.cbMcgFwDirs = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgFwDirs.sizePolicy().hasHeightForWidth())
        self.cbMcgFwDirs.setSizePolicy(sizePolicy)
        self.cbMcgFwDirs.setMinimumSize(QtCore.QSize(350, 0))
        self.cbMcgFwDirs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgFwDirs.setEditable(True)
        self.cbMcgFwDirs.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgFwDirs.setObjectName("cbMcgFwDirs")
        self.horizontalLayout_8.addWidget(self.cbMcgFwDirs)
        self.pbFwDirSel = QtWidgets.QPushButton(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbFwDirSel.sizePolicy().hasHeightForWidth())
        self.pbFwDirSel.setSizePolicy(sizePolicy)
        self.pbFwDirSel.setMinimumSize(QtCore.QSize(20, 0))
        self.pbFwDirSel.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pbFwDirSel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbFwDirSel.setObjectName("pbFwDirSel")
        self.horizontalLayout_8.addWidget(self.pbFwDirSel)
        self.pbUpdateMcgFwVersions = QtWidgets.QPushButton(self.tabRelease)
        self.pbUpdateMcgFwVersions.setMinimumSize(QtCore.QSize(210, 0))
        self.pbUpdateMcgFwVersions.setMaximumSize(QtCore.QSize(210, 16777215))
        self.pbUpdateMcgFwVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbUpdateMcgFwVersions.setCheckable(False)
        self.pbUpdateMcgFwVersions.setObjectName("pbUpdateMcgFwVersions")
        self.horizontalLayout_8.addWidget(self.pbUpdateMcgFwVersions)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.tabRelease)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.cbMcgCfgVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgCfgVersions.sizePolicy().hasHeightForWidth())
        self.cbMcgCfgVersions.setSizePolicy(sizePolicy)
        self.cbMcgCfgVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbMcgCfgVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbMcgCfgVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgCfgVersions.setEditable(True)
        self.cbMcgCfgVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgCfgVersions.setObjectName("cbMcgCfgVersions")
        self.horizontalLayout_7.addWidget(self.cbMcgCfgVersions)
        self.label_11 = QtWidgets.QLabel(self.tabRelease)
        self.label_11.setMinimumSize(QtCore.QSize(70, 0))
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.cbMcgCfgDirs = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgCfgDirs.sizePolicy().hasHeightForWidth())
        self.cbMcgCfgDirs.setSizePolicy(sizePolicy)
        self.cbMcgCfgDirs.setMinimumSize(QtCore.QSize(350, 0))
        self.cbMcgCfgDirs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgCfgDirs.setEditable(True)
        self.cbMcgCfgDirs.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgCfgDirs.setObjectName("cbMcgCfgDirs")
        self.horizontalLayout_7.addWidget(self.cbMcgCfgDirs)
        self.pbCfgDirSel = QtWidgets.QPushButton(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCfgDirSel.sizePolicy().hasHeightForWidth())
        self.pbCfgDirSel.setSizePolicy(sizePolicy)
        self.pbCfgDirSel.setMinimumSize(QtCore.QSize(20, 0))
        self.pbCfgDirSel.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pbCfgDirSel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbCfgDirSel.setObjectName("pbCfgDirSel")
        self.horizontalLayout_7.addWidget(self.pbCfgDirSel)
        self.pbUpdateMcgMasters = QtWidgets.QPushButton(self.tabRelease)
        self.pbUpdateMcgMasters.setMinimumSize(QtCore.QSize(210, 0))
        self.pbUpdateMcgMasters.setMaximumSize(QtCore.QSize(210, 16777215))
        self.pbUpdateMcgMasters.setObjectName("pbUpdateMcgMasters")
        self.horizontalLayout_7.addWidget(self.pbUpdateMcgMasters)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.tabRelease)
        self.label_21.setMinimumSize(QtCore.QSize(100, 0))
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_21.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.cbProdBaseVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbProdBaseVersions.sizePolicy().hasHeightForWidth())
        self.cbProdBaseVersions.setSizePolicy(sizePolicy)
        self.cbProdBaseVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbProdBaseVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbProdBaseVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbProdBaseVersions.setEditable(True)
        self.cbProdBaseVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbProdBaseVersions.setObjectName("cbProdBaseVersions")
        self.horizontalLayout_2.addWidget(self.cbProdBaseVersions)
        self.label_9 = QtWidgets.QLabel(self.tabRelease)
        self.label_9.setMinimumSize(QtCore.QSize(70, 0))
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.cbMcgPackDirs = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgPackDirs.sizePolicy().hasHeightForWidth())
        self.cbMcgPackDirs.setSizePolicy(sizePolicy)
        self.cbMcgPackDirs.setMinimumSize(QtCore.QSize(350, 0))
        self.cbMcgPackDirs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgPackDirs.setEditable(True)
        self.cbMcgPackDirs.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgPackDirs.setObjectName("cbMcgPackDirs")
        self.horizontalLayout_2.addWidget(self.cbMcgPackDirs)
        self.pbPackDirSel = QtWidgets.QPushButton(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbPackDirSel.sizePolicy().hasHeightForWidth())
        self.pbPackDirSel.setSizePolicy(sizePolicy)
        self.pbPackDirSel.setMinimumSize(QtCore.QSize(20, 0))
        self.pbPackDirSel.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pbPackDirSel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbPackDirSel.setObjectName("pbPackDirSel")
        self.horizontalLayout_2.addWidget(self.pbPackDirSel)
        self.pbUpdateMcgPackVersions = QtWidgets.QPushButton(self.tabRelease)
        self.pbUpdateMcgPackVersions.setMinimumSize(QtCore.QSize(210, 0))
        self.pbUpdateMcgPackVersions.setMaximumSize(QtCore.QSize(210, 16777215))
        self.pbUpdateMcgPackVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbUpdateMcgPackVersions.setObjectName("pbUpdateMcgPackVersions")
        self.horizontalLayout_2.addWidget(self.pbUpdateMcgPackVersions)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.tabRelease)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.tabRelease)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.cbPackSrcBranchVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPackSrcBranchVersions.sizePolicy().hasHeightForWidth())
        self.cbPackSrcBranchVersions.setSizePolicy(sizePolicy)
        self.cbPackSrcBranchVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbPackSrcBranchVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbPackSrcBranchVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbPackSrcBranchVersions.setEditable(True)
        self.cbPackSrcBranchVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbPackSrcBranchVersions.setObjectName("cbPackSrcBranchVersions")
        self.horizontalLayout_3.addWidget(self.cbPackSrcBranchVersions)
        self.label_7 = QtWidgets.QLabel(self.tabRelease)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.cbMcgPackTagVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgPackTagVersions.sizePolicy().hasHeightForWidth())
        self.cbMcgPackTagVersions.setSizePolicy(sizePolicy)
        self.cbMcgPackTagVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbMcgPackTagVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbMcgPackTagVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgPackTagVersions.setEditable(True)
        self.cbMcgPackTagVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgPackTagVersions.setObjectName("cbMcgPackTagVersions")
        self.horizontalLayout_3.addWidget(self.cbMcgPackTagVersions)
        self.pbCreateMcgPackTags = QtWidgets.QPushButton(self.tabRelease)
        self.pbCreateMcgPackTags.setMinimumSize(QtCore.QSize(210, 0))
        self.pbCreateMcgPackTags.setMaximumSize(QtCore.QSize(210, 16777215))
        self.pbCreateMcgPackTags.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbCreateMcgPackTags.setObjectName("pbCreateMcgPackTags")
        self.horizontalLayout_3.addWidget(self.pbCreateMcgPackTags)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tabRelease)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cbMcgFwRepoVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgFwRepoVersions.sizePolicy().hasHeightForWidth())
        self.cbMcgFwRepoVersions.setSizePolicy(sizePolicy)
        self.cbMcgFwRepoVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbMcgFwRepoVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbMcgFwRepoVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgFwRepoVersions.setEditable(True)
        self.cbMcgFwRepoVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgFwRepoVersions.setObjectName("cbMcgFwRepoVersions")
        self.horizontalLayout_4.addWidget(self.cbMcgFwRepoVersions)
        self.label_2 = QtWidgets.QLabel(self.tabRelease)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cbMcgFwInstVersions = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgFwInstVersions.sizePolicy().hasHeightForWidth())
        self.cbMcgFwInstVersions.setSizePolicy(sizePolicy)
        self.cbMcgFwInstVersions.setMinimumSize(QtCore.QSize(90, 0))
        self.cbMcgFwInstVersions.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cbMcgFwInstVersions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cbMcgFwInstVersions.setEditable(True)
        self.cbMcgFwInstVersions.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgFwInstVersions.setObjectName("cbMcgFwInstVersions")
        self.horizontalLayout_4.addWidget(self.cbMcgFwInstVersions)
        self.cbMcgFwInstDirs = QtWidgets.QComboBox(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMcgFwInstDirs.sizePolicy().hasHeightForWidth())
        self.cbMcgFwInstDirs.setSizePolicy(sizePolicy)
        self.cbMcgFwInstDirs.setMinimumSize(QtCore.QSize(300, 0))
        self.cbMcgFwInstDirs.setEditable(True)
        self.cbMcgFwInstDirs.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cbMcgFwInstDirs.setObjectName("cbMcgFwInstDirs")
        self.horizontalLayout_4.addWidget(self.cbMcgFwInstDirs)
        self.pbInstLocSel = QtWidgets.QPushButton(self.tabRelease)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbInstLocSel.sizePolicy().hasHeightForWidth())
        self.pbInstLocSel.setSizePolicy(sizePolicy)
        self.pbInstLocSel.setMinimumSize(QtCore.QSize(20, 0))
        self.pbInstLocSel.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pbInstLocSel.setObjectName("pbInstLocSel")
        self.horizontalLayout_4.addWidget(self.pbInstLocSel)
        self.pbCopyMcgFwToInstLoc = QtWidgets.QPushButton(self.tabRelease)
        self.pbCopyMcgFwToInstLoc.setMinimumSize(QtCore.QSize(175, 0))
        self.pbCopyMcgFwToInstLoc.setMaximumSize(QtCore.QSize(175, 16777215))
        self.pbCopyMcgFwToInstLoc.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbCopyMcgFwToInstLoc.setObjectName("pbCopyMcgFwToInstLoc")
        self.horizontalLayout_4.addWidget(self.pbCopyMcgFwToInstLoc)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tabRelease)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pbClearLog = QtWidgets.QPushButton(self.tabRelease)
        self.pbClearLog.setMinimumSize(QtCore.QSize(100, 0))
        self.pbClearLog.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbClearLog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pbClearLog.setObjectName("pbClearLog")
        self.horizontalLayout_5.addWidget(self.pbClearLog)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.teLog = QtWidgets.QTextEdit(self.tabRelease)
        self.teLog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.teLog.setReadOnly(True)
        self.teLog.setObjectName("teLog")
        self.verticalLayout.addWidget(self.teLog)
        self.tabWidget.addTab(self.tabRelease, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(False)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1035, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.cbMcgFwVersions)
        MainWindow.setTabOrder(self.cbMcgFwVersions, self.cbMcgFwDirs)
        MainWindow.setTabOrder(self.cbMcgFwDirs, self.pbFwDirSel)
        MainWindow.setTabOrder(self.pbFwDirSel, self.pbUpdateMcgFwVersions)
        MainWindow.setTabOrder(self.pbUpdateMcgFwVersions, self.cbMcgCfgVersions)
        MainWindow.setTabOrder(self.cbMcgCfgVersions, self.cbMcgCfgDirs)
        MainWindow.setTabOrder(self.cbMcgCfgDirs, self.pbCfgDirSel)
        MainWindow.setTabOrder(self.pbCfgDirSel, self.pbUpdateMcgMasters)
        MainWindow.setTabOrder(self.pbUpdateMcgMasters, self.cbProdBaseVersions)
        MainWindow.setTabOrder(self.cbProdBaseVersions, self.cbMcgPackDirs)
        MainWindow.setTabOrder(self.cbMcgPackDirs, self.pbPackDirSel)
        MainWindow.setTabOrder(self.pbPackDirSel, self.pbUpdateMcgPackVersions)
        MainWindow.setTabOrder(self.pbUpdateMcgPackVersions, self.cbPackSrcBranchVersions)
        MainWindow.setTabOrder(self.cbPackSrcBranchVersions, self.cbMcgPackTagVersions)
        MainWindow.setTabOrder(self.cbMcgPackTagVersions, self.pbCreateMcgPackTags)
        MainWindow.setTabOrder(self.pbCreateMcgPackTags, self.cbMcgFwRepoVersions)
        MainWindow.setTabOrder(self.cbMcgFwRepoVersions, self.cbMcgFwInstVersions)
        MainWindow.setTabOrder(self.cbMcgFwInstVersions, self.cbMcgFwInstDirs)
        MainWindow.setTabOrder(self.cbMcgFwInstDirs, self.pbInstLocSel)
        MainWindow.setTabOrder(self.pbInstLocSel, self.pbCopyMcgFwToInstLoc)
        MainWindow.setTabOrder(self.pbCopyMcgFwToInstLoc, self.pbClearLog)
        MainWindow.setTabOrder(self.pbClearLog, self.teLog)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MyToolsCollection", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "MCG Fw Version:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "MCG Fw Dir:", None, -1))
        self.pbFwDirSel.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pbUpdateMcgFwVersions.setText(QtWidgets.QApplication.translate("MainWindow", "Update MCG Firmware Versions", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "MCG Cfg Version:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "MCG Cfg Dir:", None, -1))
        self.pbCfgDirSel.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pbUpdateMcgMasters.setText(QtWidgets.QApplication.translate("MainWindow", "Update MCG Master Files", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "ProdBase Version:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Pack Dir:", None, -1))
        self.pbPackDirSel.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pbUpdateMcgPackVersions.setText(QtWidgets.QApplication.translate("MainWindow", "Update MCG Pack Files", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Branch Version:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Tag Version (Base):", None, -1))
        self.pbCreateMcgPackTags.setText(QtWidgets.QApplication.translate("MainWindow", "Create MCG Pack Tags", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Source Version:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Target Version:", None, -1))
        self.pbInstLocSel.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pbCopyMcgFwToInstLoc.setText(QtWidgets.QApplication.translate("MainWindow", "Copy MCG FW To Install Loc", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Logs:", None, -1))
        self.pbClearLog.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Log", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRelease), QtWidgets.QApplication.translate("MainWindow", "Release Actions", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Tab 2", None, -1))

